name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions: write-all

jobs:
  rebuild:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
         npm i -g pnpm
         pnpm i --shamefully-hoist --force
         pnpm run build-prod
        env:
          NODE_OPTIONS: --openssl-legacy-provider
       
      - name: Upload built-dist
        uses: actions/upload-artifact@v3.1.1
        with:
          name: built-dist
          path: dist
          
      - name: Checkout to build
        uses: actions/checkout@v3
        with:
          ref: build
      
      - name: Clean
        run: rm -rf dist/*
          
      - name: Download built-dist
        uses: actions/download-artifact@v3.0.1
        with:
          name: built-dist
          path: dist/
      
      - name: Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: "Build"
          committer_name: GitHub Actions
          committer_email: actions@github.com
